name: GeoSpatTask
channels:
  - conda-forge
  - defaults
dependencies:
  - affine=2.2.2
  - attrs=19.1.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - boost-cpp=1.69.0
  - bzip2=1.0.6
  - ca-certificates=2019.3.9
  - certifi=2019.3.9
  - click=7.0
  - click-plugins=1.1.1
  - cligj=0.5.0
  - colorama=0.4.1
  - curl=7.64.0
  - cycler=0.10.0
  - decorator=4.4.0
  - defusedxml=0.5.0
  - descartes=1.1.0
  - entrypoints=0.3
  - expat=2.2.5
  - fiona=1.8.6
  - flake8=3.7.7
  - flake8-polyfill=1.0.2
  - freetype=2.10.0
  - freexl=1.0.5
  - gdal=2.4.1
  - geopandas=0.5.0
  - geos=3.7.1
  - geotiff=1.5.1
  - gettext=0.19.8.1
  - glib=2.58.3
  - hdf4=4.2.13
  - hdf5=1.10.4
  - icc_rt=2019.0.0
  - icu=58.2
  - intel-openmp=2019.3
  - ipykernel=5.1.0=
  - ipython=7.5.0
  - ipython_genutils=0.2.0
  - jedi=0.13.3
  - jinja2=2.10.1
  - jpeg=9c
  - jsonschema=3.0.1
  - jupyter_client=5.2.4
  - jupyter_core=4.4.0
  - kealib=1.4.10
  - kiwisolver=1.1.0
  - krb5=1.16.3
  - libblas=3.8.0
  - libboost=1.67.0
  - libcblas=3.8.0
  - libcurl=7.64.0
  - libffi=3.2.1
  - libgdal=2.4.1
  - libiconv=1.15
  - libkml=1.3.0
  - liblapack=3.8.0
  - libnetcdf=4.6.2
  - libpng=1.6.37
  - libpq=11.2
  - libsodium=1.0.16
  - libspatialindex=1.8.5
  - libspatialite=4.3.0a
  - libssh2=1.8.2
  - libtiff=4.0.10
  - libxml2=2.9.9
  - m2w64-expat=2.1.1
  - m2w64-gcc-libgfortran=5.3.0
  - m2w64-gcc-libs=5.3.0
  - m2w64-gcc-libs-core=5.3.0
  - m2w64-gettext=0.19.7
  - m2w64-gmp=6.1.0
  - m2w64-libiconv=1.14
  - m2w64-libwinpthread-git=5.0.0.4634.697f757
  - m2w64-xz=5.2.2
  - mando=0.6.4
  - mapclassify=2.0.1
  - markupsafe=1.1.1
  - matplotlib=3.0.3
  - matplotlib-base=3.0.3
  - mccabe=0.6.1
  - mistune=0.8.4
  - mkl=2019.3
  - mpmath=1.1.0
  - msys2-conda-epoch=20160418
  - munch=2.3.2
  - nbconvert=5.5.0
  - nbformat=4.4.0
  - notebook=5.7.8
  - numpy=1.16.3
  - openjpeg=2.3.1
  - openssl=1.1.1b
  - palettable=3.1.1
  - pandas=0.24.2
  - pandoc=2.7.2
  - pandocfilters=1.4.2
  - parso=0.4.0
  - patsy=0.5.1
  - pcre=8.41
  - pickleshare=0.7.5
  - pip=19.1
  - poppler=0.67.0
  - poppler-data=0.4.9
  - postgresql=11.2
  - proj4=6.0.0
  - prometheus_client=0.6.0
  - prompt_toolkit=2.0.9
  - pycodestyle=2.5.0
  - pyflakes=2.1.1
  - pygments=2.3.1
  - pyparsing=2.4.0
  - pyproj=2.1.3
  - pyqt=5.9.2
  - pyrsistent=0.15.1
  - pysal=2.0.0
  - python=3.7.1
  - python-dateutil=2.8.0
  - pytz=2019.1
  - pywinpty=0.5.5
  - pyzmq=18.0.1
  - qt=5.9.7
  - radon=3.0.1
  - rasterio=1.0.22
  - rtree=0.8.3
  - scipy=1.2.1
  - seaborn=0.9.0
  - send2trash=1.5.0
  - setuptools=41.0.1
  - shapely=1.6.4
  - sip=4.19.8
  - six=1.12.0
  - snuggs=1.4.3
  - sqlite=3.26.0
  - statsmodels=0.9.0
  - terminado=0.8.2
  - testpath=0.4.2
  - tk=8.6.9
  - tornado=6.0.2
  - traitlets=4.3.2
  - vc=14.1
  - vs2015_runtime=14.15
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.1
  - wincertstore=0.2
  - winpty=0.4.3
  - xerces-c=3.2.2
  - xz=5.2.4
  - zeromq=4.3.1
  - zlib=1.2.11
  - pip:
    - imageio==2.5.0
    - networkx==2.3
    - pillow==6.0.0
    - pycrs==1.0.1
    - pywavelets==1.0.3
    - scikit-image==0.15.0


